name: WorldFixer
version: 1.0.4
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
main: worldfixer\WorldFixer
authors: [CreeperFace, GamakCZ]
description: Now you can block, slabs easily and quickly!
        
permissions:
  wf:
    description: Permission to do all actions
    children:
      wf.command:
        description: Permission to run all commands
        children:
          wf.command.fix:
            description: allows fix grass color and wooden slabs in your world
            default: op
          wf.command.wand:
            description: allows select an area
            default: op
